spring:
  application:
    name: configdemo
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

build:
  id: ${BUILD_ID}
  version: ${BUILD_VERSION}
  name: ${BUILD_NAME}
