spring:
  application:
    name: configdemo
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: prod
#build:
#  id: ${ID}
#  version: ${VERSION}
#  name: ${NAME}

management:
  endpoints:
    web:
      exposure:
        include: refresh
